module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,2.9,True,2022-09-13T07:00:14,,
cowidev.vax.batch.australia,6.26,True,2022-09-13T07:00:17,,
cowidev.vax.batch.austria,1.94,True,2022-09-13T07:00:13,,
cowidev.vax.batch.belgium,1.56,True,2022-09-13T07:00:12,,
cowidev.vax.batch.bolivia,1.81,True,2022-09-13T07:00:13,,
cowidev.vax.batch.canada,5.88,True,2022-09-13T07:00:18,,
cowidev.vax.batch.chile,1.14,True,2022-09-13T07:00:14,,
cowidev.vax.batch.czechia,1.16,False,2022-09-13T07:03:31,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/czechia.py"", line 183, in main
    Czechia().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/czechia.py"", line 168, in export
    base = read(self.source_url).pipe(base_pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/czechia.py"", line 66, in base_pipeline
    return df.pipe(check_vaccine_names).pipe(translate_vaccine_names)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/czechia.py"", line 45, in check_vaccine_names
    raise ValueError(""Found unknown vaccines: {}"".format(unknown_vaccines))
ValueError: Found unknown vaccines: {'Comirnaty Original/Omicron BA.1'}
",Found unknown vaccines: {'Comirnaty Original/Omicron BA.1'}
cowidev.vax.batch.denmark,1.81,True,2022-09-13T07:00:15,,
cowidev.vax.batch.ecdc,122.11,True,2022-09-13T07:02:16,,
cowidev.vax.batch.ecuador,1.92,True,2022-09-13T07:00:17,,
cowidev.vax.batch.estonia,0.65,True,2022-09-13T07:00:18,,
cowidev.vax.batch.france,0.67,True,2022-09-13T07:00:18,,
cowidev.vax.batch.germany,2.05,True,2022-09-13T07:00:20,,
cowidev.vax.batch.greece,2.73,True,2022-09-13T07:00:21,,
cowidev.vax.batch.hong_kong,12.46,True,2022-09-13T07:00:31,,
cowidev.vax.batch.indonesia,,,2022-09-13T07:00:19,,
cowidev.vax.batch.ireland,0.36,True,2022-09-13T07:00:19,,
cowidev.vax.batch.israel,9.69,True,2022-09-13T07:00:29,,
cowidev.vax.batch.italy,10.7,True,2022-09-13T07:00:30,,
cowidev.vax.batch.japan,1.39,False,2022-09-13T07:03:32,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 236, in main
    Japan().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 220, in export
    df = self.read().pipe(self.pipeline_base)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 156, in read
    df_latest = self.read_latest().pipe(self.pipe_latest)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 88, in read_latest
    dfs.append(self._read_xlsx(self.source_url, self.sheets, self.metrics))
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 97, in _read_xlsx
    xlsx = pd.ExcelFile(url)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/excel/_base.py"", line 1191, in __init__
    ext = inspect_excel_format(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/excel/_base.py"", line 1070, in inspect_excel_format
    with get_handle(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/common.py"", line 609, in get_handle
    ioargs = _get_filepath_or_buffer(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/common.py"", line 312, in _get_filepath_or_buffer
    with urlopen(req_info) as req:
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/common.py"", line 212, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 214, in urlopen
    return opener.open(url, data, timeout)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 523, in open
    response = meth(req, response)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 632, in http_response
    response = self.parent.error(
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 561, in error
    return self._call_chain(*args)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 494, in _call_chain
    result = func(*args)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
",HTTP Error 404: Not Found
cowidev.vax.batch.jersey,1.46,True,2022-09-13T07:00:30,,
cowidev.vax.batch.latvia,27.44,True,2022-09-13T07:00:58,,
cowidev.vax.batch.lithuania,4.29,True,2022-09-13T07:00:35,,
cowidev.vax.batch.luxembourg,2.16,True,2022-09-13T07:00:33,,
cowidev.vax.batch.malaysia,0.87,True,2022-09-13T07:00:32,,
cowidev.vax.batch.malta,1.53,True,2022-09-13T07:00:33,,
cowidev.vax.batch.netherlands,,,2022-09-13T07:00:33,,
cowidev.vax.batch.new_zealand,20.62,True,2022-09-13T07:00:53,,
cowidev.vax.batch.norway,1.98,True,2022-09-13T07:00:35,,
cowidev.vax.batch.peru,4.33,True,2022-09-13T07:00:39,,
cowidev.vax.batch.portugal,,,2022-09-13T07:00:35,,
cowidev.vax.batch.romania,24.51,True,2022-09-13T07:01:00,,
cowidev.vax.batch.saudi_arabia,6.39,True,2022-09-13T07:00:45,,
cowidev.vax.batch.singapore,5.48,True,2022-09-13T07:00:51,,
cowidev.vax.batch.slovakia,83.34,True,2022-09-13T07:02:14,,
cowidev.vax.batch.slovenia,5.4,True,2022-09-13T07:00:59,,
cowidev.vax.batch.south_korea,54.48,True,2022-09-13T07:01:52,,
cowidev.vax.batch.spc,15.45,True,2022-09-13T07:01:14,,
cowidev.vax.batch.sweden,13.49,True,2022-09-13T07:01:13,,
cowidev.vax.batch.switzerland,43.26,True,2022-09-13T07:01:56,,
cowidev.vax.batch.trinidad_and_tobago,1.95,True,2022-09-13T07:01:16,,
cowidev.vax.batch.ukraine,,,2022-09-13T07:01:16,,
cowidev.vax.batch.united_kingdom,10.48,True,2022-09-13T07:01:27,,
cowidev.vax.batch.united_states,54.68,True,2022-09-13T07:02:21,,
cowidev.vax.batch.uruguay,3.69,True,2022-09-13T07:01:56,,
cowidev.vax.batch.zimbabwe,1.39,True,2022-09-13T07:01:57,,
cowidev.vax.incremental.africacdc,,,2022-09-13T07:01:56,,
cowidev.vax.incremental.antigua_barbuda,4.07,True,2022-09-13T07:02:00,,
cowidev.vax.incremental.aruba,1.41,True,2022-09-13T07:01:59,,
cowidev.vax.incremental.azerbaijan,,,2022-09-13T07:01:59,,
cowidev.vax.incremental.bahrain,5.03,True,2022-09-13T07:02:04,,
cowidev.vax.incremental.bangladesh,25.82,True,2022-09-13T07:02:26,,
cowidev.vax.incremental.barbados,10.86,True,2022-09-13T07:02:15,,
cowidev.vax.incremental.brazil,0.25,True,2022-09-13T07:02:14,,
cowidev.vax.incremental.bulgaria,1.85,True,2022-09-13T07:02:16,,
cowidev.vax.incremental.china,46.97,True,2022-09-13T07:03:02,,
cowidev.vax.incremental.costa_rica,,,2022-09-13T07:02:16,,
cowidev.vax.incremental.croatia,0.19,True,2022-09-13T07:02:16,,
cowidev.vax.incremental.cuba,2.23,True,2022-09-13T07:02:18,,
cowidev.vax.incremental.curacao,0.38,True,2022-09-13T07:02:17,,
cowidev.vax.incremental.cyprus,1.03,True,2022-09-13T07:02:18,,
cowidev.vax.incremental.dominican_republic,6.01,True,2022-09-13T07:02:24,,
cowidev.vax.incremental.el_salvador,0.85,True,2022-09-13T07:02:19,,
cowidev.vax.incremental.faeroe_islands,0.49,True,2022-09-13T07:02:20,,
cowidev.vax.incremental.fiji,0.0,True,2022-09-13T07:02:20,,
cowidev.vax.incremental.finland,0.21,True,2022-09-13T07:02:20,,
cowidev.vax.incremental.gabon,,,2022-09-13T07:02:20,,
cowidev.vax.incremental.georgia,0.64,True,2022-09-13T07:02:20,,
cowidev.vax.incremental.greenland,1.01,True,2022-09-13T07:02:21,,
cowidev.vax.incremental.guatemala,,,2022-09-13T07:02:21,,
cowidev.vax.incremental.guernsey,0.16,True,2022-09-13T07:02:22,,
cowidev.vax.incremental.hungary,0.98,True,2022-09-13T07:02:22,,
cowidev.vax.incremental.iceland,0.21,True,2022-09-13T07:02:22,,
cowidev.vax.incremental.india,1.13,True,2022-09-13T07:02:23,,
cowidev.vax.incremental.iran,,,2022-09-13T07:02:22,,
cowidev.vax.incremental.isle_of_man,0.7,True,2022-09-13T07:02:23,,
cowidev.vax.incremental.jamaica,2.31,True,2022-09-13T07:02:25,,
cowidev.vax.incremental.kazakhstan,8.24,True,2022-09-13T07:02:31,,
cowidev.vax.incremental.kosovo,22.67,False,2022-09-13T07:03:55,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 82, in main
    Kosovo().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 77, in export
    df = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 23, in read
    df = self._parse_data(soup)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 32, in _parse_data
    soup = get_soup(link, verify=False)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://msh.rks-gov.net/10.230.0.57+9000/coviddashboard.html not reached! Error code 404 Not Found
",Source https://msh.rks-gov.net/10.230.0.57+9000/coviddashboard.html not reached! Error code 404 Not Found
cowidev.vax.incremental.kyrgyzstan,1.97,True,2022-09-13T07:02:27,,
cowidev.vax.incremental.laos,2.46,True,2022-09-13T07:02:29,,
cowidev.vax.incremental.macao,17.67,True,2022-09-13T07:02:45,,
cowidev.vax.incremental.moldova,40.08,False,2022-09-13T07:04:35,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 96, in create_connection
    raise err
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 699, in urlopen
    httplib_response = self._make_request(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 382, in _make_request
    self._validate_conn(conn)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 1010, in _validate_conn
    conn.connect()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 358, in connect
    conn = self._new_conn()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f69ccf0e5b0>, 'Connection to vaccinare.gov.md timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 755, in urlopen
    retries = retries.increment(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/retry.py"", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='vaccinare.gov.md', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f69ccf0e5b0>, 'Connection to vaccinare.gov.md timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/moldova.py"", line 59, in main
    Moldova().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/moldova.py"", line 54, in export
    df = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/moldova.py"", line 17, in read
    soup = get_soup(self.source_url)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='vaccinare.gov.md', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f69ccf0e5b0>, 'Connection to vaccinare.gov.md timed out. (connect timeout=20)'))
","HTTPSConnectionPool(host='vaccinare.gov.md', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f69ccf0e5b0>, 'Connection to vaccinare.gov.md timed out. (connect timeout=20)'))"
cowidev.vax.incremental.monaco,28.18,True,2022-09-13T07:03:00,,
cowidev.vax.incremental.mongolia,0.83,True,2022-09-13T07:02:39,,
cowidev.vax.incremental.montenegro,0.09,True,2022-09-13T07:02:39,,
cowidev.vax.incremental.morocco,,,2022-09-13T07:02:39,,
cowidev.vax.incremental.myanmar,,,2022-09-13T07:02:39,,
cowidev.vax.incremental.nepal,,,2022-09-13T07:02:39,,
cowidev.vax.incremental.north_macedonia,,,2022-09-13T07:02:39,,
cowidev.vax.incremental.northern_cyprus,0.76,True,2022-09-13T07:02:40,,
cowidev.vax.incremental.paho,49.87,True,2022-09-13T07:03:30,,
cowidev.vax.incremental.pakistan,1.5,True,2022-09-13T07:02:46,,
cowidev.vax.incremental.philippines,,,2022-09-13T07:02:46,,
cowidev.vax.incremental.poland,0.3,True,2022-09-13T07:02:47,,
cowidev.vax.incremental.qatar,,,2022-09-13T07:02:47,,
cowidev.vax.incremental.russia,0.54,False,2022-09-13T07:04:35,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 80, in main
    Russia().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 66, in export
    data = read(source).pipe(pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 11, in read
    soup = get_soup(source)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://gogov.ru/articles/covid-v-stats not reached! Error code 502 Bad Gateway
",Source https://gogov.ru/articles/covid-v-stats not reached! Error code 502 Bad Gateway
cowidev.vax.incremental.saint_lucia,,,2022-09-13T07:02:47,,
cowidev.vax.incremental.serbia,7.95,True,2022-09-13T07:02:55,,
cowidev.vax.incremental.south_africa,8.21,True,2022-09-13T07:03:04,,
cowidev.vax.incremental.spain,4.2,True,2022-09-13T07:03:04,,
cowidev.vax.incremental.sri_lanka,,,2022-09-13T07:03:02,,
cowidev.vax.incremental.suriname,15.1,True,2022-09-13T07:03:17,,
cowidev.vax.incremental.taiwan,4.34,True,2022-09-13T07:03:08,,
cowidev.vax.incremental.thailand,3.55,True,2022-09-13T07:03:07,,
cowidev.vax.incremental.turkey,0.66,True,2022-09-13T07:03:08,,
cowidev.vax.incremental.united_arab_emirates,,,2022-09-13T07:03:08,,
cowidev.vax.incremental.vietnam,,,2022-09-13T07:03:08,,
cowidev.vax.incremental.who,3.78,True,2022-09-13T07:03:12,,
cowidev.vax.incremental.zambia,0.71,True,2022-09-13T07:03:09,,
