module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,4.38,True,2022-07-13T07:00:16,,
cowidev.vax.batch.australia,2.47,True,2022-07-13T07:00:14,,
cowidev.vax.batch.austria,,,2022-07-13T07:00:12,,
cowidev.vax.batch.belgium,2.75,True,2022-07-13T07:00:14,,
cowidev.vax.batch.bolivia,2.69,True,2022-07-13T07:00:14,,
cowidev.vax.batch.canada,5.12,True,2022-07-13T07:00:17,,
cowidev.vax.batch.chile,1.71,True,2022-07-13T07:00:16,,
cowidev.vax.batch.czechia,4.58,True,2022-07-13T07:00:19,,
cowidev.vax.batch.denmark,4.83,True,2022-07-13T07:00:19,,
cowidev.vax.batch.ecdc,60.06,False,2022-07-13T07:04:25,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 96, in create_connection
    raise err
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 699, in urlopen
    httplib_response = self._make_request(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 382, in _make_request
    self._validate_conn(conn)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 1010, in _validate_conn
    conn.connect()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 358, in connect
    conn = self._new_conn()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f47eaaf0640>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 755, in urlopen
    retries = retries.increment(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/retry.py"", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f47eaaf0640>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 506, in main
    ECDC().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 496, in export
    df = self.read().pipe(self.pipe_base)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 111, in read
    df = read_csv_from_url(self.source_url, timeout=30)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/download.py"", line 39, in read_csv_from_url
    download_file_from_url(url, tmp.name, timeout=timeout, verify=verify, ciphers_low=ciphers_low)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/download.py"", line 52, in download_file_from_url
    r = requests.get(url, stream=True, timeout=timeout, verify=verify)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f47eaaf0640>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)'))
","HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f47eaaf0640>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)'))"
cowidev.vax.batch.ecuador,1.52,True,2022-07-13T07:00:18,,
cowidev.vax.batch.estonia,0.93,True,2022-07-13T07:00:18,,
cowidev.vax.batch.france,1.06,True,2022-07-13T07:00:19,,
cowidev.vax.batch.germany,1.76,True,2022-07-13T07:00:19,,
cowidev.vax.batch.greece,3.73,True,2022-07-13T07:00:22,,
cowidev.vax.batch.hong_kong,12.62,True,2022-07-13T07:00:32,,
cowidev.vax.batch.indonesia,,,2022-07-13T07:00:19,,
cowidev.vax.batch.ireland,0.42,True,2022-07-13T07:00:20,,
cowidev.vax.batch.israel,11.05,True,2022-07-13T07:00:31,,
cowidev.vax.batch.italy,13.29,True,2022-07-13T07:00:33,,
cowidev.vax.batch.japan,74.64,True,2022-07-13T07:01:37,,
cowidev.vax.batch.jersey,2.16,True,2022-07-13T07:00:33,,
cowidev.vax.batch.latvia,28.56,True,2022-07-13T07:01:00,,
cowidev.vax.batch.lithuania,3.03,True,2022-07-13T07:00:36,,
cowidev.vax.batch.luxembourg,2.15,True,2022-07-13T07:00:35,,
cowidev.vax.batch.malaysia,2.06,True,2022-07-13T07:00:37,,
cowidev.vax.batch.malta,1.28,True,2022-07-13T07:00:37,,
cowidev.vax.batch.netherlands,,,2022-07-13T07:00:37,,
cowidev.vax.batch.new_zealand,30.87,True,2022-07-13T07:01:08,,
cowidev.vax.batch.norway,1.03,True,2022-07-13T07:00:38,,
cowidev.vax.batch.peru,4.12,True,2022-07-13T07:00:42,,
cowidev.vax.batch.portugal,,,2022-07-13T07:00:42,,
cowidev.vax.batch.romania,30.76,True,2022-07-13T07:01:13,,
cowidev.vax.batch.saudi_arabia,10.71,True,2022-07-13T07:01:11,,
cowidev.vax.batch.singapore,2.93,True,2022-07-13T07:01:11,,
cowidev.vax.batch.slovakia,59.69,True,2022-07-13T07:02:10,,
cowidev.vax.batch.slovenia,1.28,True,2022-07-13T07:01:12,,
cowidev.vax.batch.south_korea,59.62,True,2022-07-13T07:02:12,,
cowidev.vax.batch.spc,4.44,False,2022-07-13T07:04:30,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/spc.py"", line 220, in main
    SPC().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/spc.py"", line 214, in export
    data = self.read()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/spc.py"", line 59, in read
    return self.parse_data(data)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/spc.py"", line 73, in parse_data
    return self._build_df_list(vaccination_data)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/spc.py"", line 103, in _build_df_list
    data[k] = self._build_df(v, k)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/spc.py"", line 135, in _build_df
    df = df.pipe(make_monotonic)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/utils/utils.py"", line 44, in make_monotonic
    raise Exception(
Exception: 50 rows have been removed. That is more than maximum allowed (10) by make_monotonic() - check the data. Check 
          date  ...  vaccine
9   2021-07-13  ...      NaN
10  2021-07-20  ...      NaN
11  2021-07-27  ...      NaN
12  2021-08-02  ...      NaN
13  2021-08-09  ...      NaN
14  2021-08-16  ...      NaN
15  2021-08-23  ...      NaN
16  2021-08-31  ...      NaN
17  2021-09-07  ...      NaN
18  2021-09-14  ...      NaN
19  2021-09-21  ...      NaN
20  2021-09-28  ...      NaN
21  2021-10-05  ...      NaN
22  2021-10-12  ...      NaN
23  2021-10-18  ...      NaN
24  2021-10-25  ...      NaN
25  2021-11-01  ...      NaN
26  2021-11-08  ...      NaN
27  2021-11-15  ...      NaN
28  2021-11-22  ...      NaN
29  2021-11-30  ...      NaN
30  2021-12-06  ...      NaN
31  2021-12-13  ...      NaN
32  2021-12-20  ...      NaN
33  2022-01-04  ...      NaN
34  2022-01-11  ...      NaN
35  2022-01-18  ...      NaN
36  2022-01-24  ...      NaN
37  2022-01-31  ...      NaN
38  2022-02-07  ...      NaN
39  2022-02-14  ...      NaN
40  2022-02-21  ...      NaN
41  2022-02-28  ...      NaN
42  2022-03-07  ...      NaN
43  2022-03-14  ...      NaN
44  2022-03-21  ...      NaN
45  2022-03-28  ...      NaN
46  2022-04-04  ...      NaN
47  2022-04-11  ...      NaN
48  2022-04-18  ...      NaN
49  2022-04-25  ...      NaN
50  2022-05-02  ...      NaN
51  2022-05-09  ...      NaN
52  2022-05-16  ...      NaN
53  2022-05-23  ...      NaN
54  2022-05-30  ...      NaN
55  2022-06-06  ...      NaN
56  2022-06-13  ...      NaN
57  2022-06-20  ...      NaN
58  2022-06-27  ...      NaN

[50 rows x 8 columns]
","50 rows have been removed. That is more than maximum allowed (10) by make_monotonic() - check the data. Check 
          date  ...  vaccine
9   2021-07-13  ...      NaN
10  2021-07-20  ...      NaN
11  2021-07-27  ...      NaN
12  2021-08-02  ...      NaN
13  2021-08-09  ...      NaN
14  2021-08-16  ...      NaN
15  2021-08-23  ...      NaN
16  2021-08-31  ...      NaN
17  2021-09-07  ...      NaN
18  2021-09-14  ...      NaN
19  2021-09-21  ...      NaN
20  2021-09-28  ...      NaN
21  2021-10-05  ...      NaN
22  2021-10-12  ...      NaN
23  2021-10-18  ...      NaN
24  2021-10-25  ...      NaN
25  2021-11-01  ...      NaN
26  2021-11-08  ...      NaN
27  2021-11-15  ...      NaN
28  2021-11-22  ...      NaN
29  2021-11-30  ...      NaN
30  2021-12-06  ...      NaN
31  2021-12-13  ...      NaN
32  2021-12-20  ...      NaN
33  2022-01-04  ...      NaN
34  2022-01-11  ...      NaN
35  2022-01-18  ...      NaN
36  2022-01-24  ...      NaN
37  2022-01-31  ...      NaN
38  2022-02-07  ...      NaN
39  2022-02-14  ...      NaN
40  2022-02-21  ...      NaN
41  2022-02-28  ...      NaN
42  2022-03-07  ...      NaN
43  2022-03-14  ...      NaN
44  2022-03-21  ...      NaN
45  2022-03-28  ...      NaN
46  2022-04-04  ...      NaN
47  2022-04-11  ...      NaN
48  2022-04-18  ...      NaN
49  2022-04-25  ...      NaN
50  2022-05-02  ...      NaN
51  2022-05-09  ...      NaN
52  2022-05-16  ...      NaN
53  2022-05-23  ...      NaN
54  2022-05-30  ...      NaN
55  2022-06-06  ...      NaN
56  2022-06-13  ...      NaN
57  2022-06-20  ...      NaN
58  2022-06-27  ...      NaN

[50 rows x 8 columns]"
cowidev.vax.batch.sweden,19.36,True,2022-07-13T07:01:36,,
cowidev.vax.batch.switzerland,62.48,True,2022-07-13T07:02:22,,
cowidev.vax.batch.trinidad_and_tobago,1.8,True,2022-07-13T07:01:38,,
cowidev.vax.batch.ukraine,,,2022-07-13T07:01:37,,
cowidev.vax.batch.united_kingdom,8.73,True,2022-07-13T07:01:46,,
cowidev.vax.batch.united_states,41.99,True,2022-07-13T07:02:20,,
cowidev.vax.batch.uruguay,4.27,True,2022-07-13T07:01:50,,
cowidev.vax.batch.zimbabwe,0.89,True,2022-07-13T07:01:51,,
cowidev.vax.incremental.africacdc,,,2022-07-13T07:01:51,,
cowidev.vax.incremental.antigua_barbuda,4.14,True,2022-07-13T07:01:55,,
cowidev.vax.incremental.aruba,1.45,True,2022-07-13T07:01:56,,
cowidev.vax.incremental.azerbaijan,14.74,True,2022-07-13T07:02:11,,
cowidev.vax.incremental.bahrain,1.58,True,2022-07-13T07:02:12,,
cowidev.vax.incremental.bangladesh,15.03,True,2022-07-13T07:02:26,,
cowidev.vax.incremental.barbados,1.16,False,2022-07-13T07:04:31,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/barbados.py"", line 96, in main
    Barbados().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/barbados.py"", line 91, in export
    df = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/barbados.py"", line 35, in read
    df = self._parse_data(soup)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/barbados.py"", line 41, in _parse_data
    link = soup.find(""a"", text=re.compile(self.regex[""title""]))[""href""]
TypeError: 'NoneType' object is not subscriptable
",'NoneType' object is not subscriptable
cowidev.vax.incremental.brazil,0.07,True,2022-07-13T07:02:12,,
cowidev.vax.incremental.bulgaria,1.14,True,2022-07-13T07:02:13,,
cowidev.vax.incremental.china,71.42,True,2022-07-13T07:05:42,,
cowidev.vax.incremental.costa_rica,,,2022-07-13T07:02:15,,
cowidev.vax.incremental.croatia,0.14,True,2022-07-13T07:02:15,,
cowidev.vax.incremental.cuba,2.4,True,2022-07-13T07:02:18,,
cowidev.vax.incremental.curacao,0.41,True,2022-07-13T07:02:18,,
cowidev.vax.incremental.cyprus,1.14,True,2022-07-13T07:02:19,,
cowidev.vax.incremental.dominican_republic,6.85,True,2022-07-13T07:02:26,,
cowidev.vax.incremental.el_salvador,1.12,True,2022-07-13T07:02:21,,
cowidev.vax.incremental.faeroe_islands,0.37,True,2022-07-13T07:02:22,,
cowidev.vax.incremental.fiji,0.0,True,2022-07-13T07:02:22,,
cowidev.vax.incremental.finland,0.28,True,2022-07-13T07:02:22,,
cowidev.vax.incremental.gabon,,,2022-07-13T07:02:22,,
cowidev.vax.incremental.georgia,0.57,True,2022-07-13T07:02:22,,
cowidev.vax.incremental.greenland,0.5,True,2022-07-13T07:02:22,,
cowidev.vax.incremental.guatemala,,,2022-07-13T07:02:22,,
cowidev.vax.incremental.guernsey,0.26,True,2022-07-13T07:02:23,,
cowidev.vax.incremental.hungary,1.06,True,2022-07-13T07:02:24,,
cowidev.vax.incremental.iceland,0.26,True,2022-07-13T07:02:23,,
cowidev.vax.incremental.india,0.78,False,2022-07-13T07:05:43,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/socket.py"", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 699, in urlopen
    httplib_response = self._make_request(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 382, in _make_request
    self._validate_conn(conn)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 1010, in _validate_conn
    conn.connect()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 358, in connect
    conn = self._new_conn()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f47eae6e880>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 755, in urlopen
    retries = retries.increment(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/retry.py"", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.cowin.gov.in', port=443): Max retries exceeded with url: /api/v1/reports/v2/getPublicReports?state_id=&district_id=&date=2022-07-13 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f47eae6e880>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/india.py"", line 100, in main
    India().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/india.py"", line 86, in export
    data = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/india.py"", line 27, in read
    data = request_json(self.source_url[self.source_name])
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 106, in request_json
    text = request_text(url, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 127, in request_text
    soup = get_soup(url, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.cowin.gov.in', port=443): Max retries exceeded with url: /api/v1/reports/v2/getPublicReports?state_id=&district_id=&date=2022-07-13 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f47eae6e880>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
","HTTPSConnectionPool(host='api.cowin.gov.in', port=443): Max retries exceeded with url: /api/v1/reports/v2/getPublicReports?state_id=&district_id=&date=2022-07-13 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f47eae6e880>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"
cowidev.vax.incremental.iran,1.81,True,2022-07-13T07:02:25,,
cowidev.vax.incremental.isle_of_man,0.46,True,2022-07-13T07:02:24,,
cowidev.vax.incremental.jamaica,2.32,True,2022-07-13T07:02:27,,
cowidev.vax.incremental.kazakhstan,8.84,True,2022-07-13T07:02:34,,
cowidev.vax.incremental.kosovo,1.88,True,2022-07-13T07:02:28,,
cowidev.vax.incremental.kyrgyzstan,2.56,True,2022-07-13T07:02:29,,
cowidev.vax.incremental.laos,2.18,True,2022-07-13T07:02:29,,
cowidev.vax.incremental.macao,20.28,True,2022-07-13T07:02:48,,
cowidev.vax.incremental.moldova,0.94,True,2022-07-13T07:02:30,,
cowidev.vax.incremental.monaco,28.91,True,2022-07-13T07:02:58,,
cowidev.vax.incremental.mongolia,1.14,True,2022-07-13T07:02:31,,
cowidev.vax.incremental.montenegro,0.12,True,2022-07-13T07:02:31,,
cowidev.vax.incremental.morocco,,,2022-07-13T07:02:31,,
cowidev.vax.incremental.myanmar,,,2022-07-13T07:02:31,,
cowidev.vax.incremental.nepal,,,2022-07-13T07:02:31,,
cowidev.vax.incremental.north_macedonia,,,2022-07-13T07:02:31,,
cowidev.vax.incremental.northern_cyprus,1.02,True,2022-07-13T07:02:32,,
cowidev.vax.incremental.paho,52.73,True,2022-07-13T07:03:25,,
cowidev.vax.incremental.pakistan,1.73,True,2022-07-13T07:02:36,,
cowidev.vax.incremental.philippines,,,2022-07-13T07:02:36,,
cowidev.vax.incremental.poland,0.3,True,2022-07-13T07:02:36,,
cowidev.vax.incremental.qatar,,,2022-07-13T07:02:36,,
cowidev.vax.incremental.russia,0.7,False,2022-07-13T07:05:44,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 64, in main
    data = read(source).pipe(pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 11, in read
    soup = get_soup(source)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://gogov.ru/articles/covid-v-stats not reached! Error code 502 Bad Gateway
",Source https://gogov.ru/articles/covid-v-stats not reached! Error code 502 Bad Gateway
cowidev.vax.incremental.saint_lucia,,,2022-07-13T07:02:37,,
cowidev.vax.incremental.serbia,6.07,True,2022-07-13T07:02:44,,
cowidev.vax.incremental.south_africa,7.25,True,2022-07-13T07:02:51,,
cowidev.vax.incremental.spain,3.99,True,2022-07-13T07:02:52,,
cowidev.vax.incremental.sri_lanka,,,2022-07-13T07:02:51,,
cowidev.vax.incremental.suriname,15.74,True,2022-07-13T07:03:07,,
cowidev.vax.incremental.taiwan,7.62,True,2022-07-13T07:03:00,,
cowidev.vax.incremental.thailand,1.91,True,2022-07-13T07:03:00,,
cowidev.vax.incremental.turkey,0.65,True,2022-07-13T07:03:00,,
cowidev.vax.incremental.united_arab_emirates,,,2022-07-13T07:03:00,,
cowidev.vax.incremental.vietnam,,,2022-07-13T07:03:00,,
cowidev.vax.incremental.who,5.21,True,2022-07-13T07:03:05,,
cowidev.vax.incremental.zambia,1.02,True,2022-07-13T07:03:01,,
