module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,3.78,True,2022-07-31T07:00:13,,
cowidev.vax.batch.australia,1.75,True,2022-07-31T07:00:11,,
cowidev.vax.batch.austria,,,2022-07-31T07:00:09,,
cowidev.vax.batch.belgium,2.13,True,2022-07-31T07:00:11,,
cowidev.vax.batch.bolivia,2.22,True,2022-07-31T07:00:11,,
cowidev.vax.batch.canada,6.72,True,2022-07-31T07:00:16,,
cowidev.vax.batch.chile,0.82,True,2022-07-31T07:00:12,,
cowidev.vax.batch.czechia,3.14,True,2022-07-31T07:00:14,,
cowidev.vax.batch.denmark,3.4,True,2022-07-31T07:00:15,,
cowidev.vax.batch.ecdc,60.08,False,2022-07-31T07:03:20,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 96, in create_connection
    raise err
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 699, in urlopen
    httplib_response = self._make_request(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 382, in _make_request
    self._validate_conn(conn)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 1010, in _validate_conn
    conn.connect()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 358, in connect
    conn = self._new_conn()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f52185a85b0>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 755, in urlopen
    retries = retries.increment(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/retry.py"", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f52185a85b0>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 506, in main
    ECDC().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 496, in export
    df = self.read().pipe(self.pipe_base)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 111, in read
    df = read_csv_from_url(self.source_url, timeout=30)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/download.py"", line 39, in read_csv_from_url
    download_file_from_url(url, tmp.name, timeout=timeout, verify=verify, ciphers_low=ciphers_low)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/download.py"", line 52, in download_file_from_url
    r = requests.get(url, stream=True, timeout=timeout, verify=verify)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f52185a85b0>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)'))
","HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f52185a85b0>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)'))"
cowidev.vax.batch.ecuador,1.53,True,2022-07-31T07:00:15,,
cowidev.vax.batch.estonia,0.55,True,2022-07-31T07:00:15,,
cowidev.vax.batch.france,0.43,True,2022-07-31T07:00:15,,
cowidev.vax.batch.germany,1.54,True,2022-07-31T07:00:16,,
cowidev.vax.batch.greece,2.51,True,2022-07-31T07:00:17,,
cowidev.vax.batch.hong_kong,12.56,True,2022-07-31T07:00:28,,
cowidev.vax.batch.indonesia,,,2022-07-31T07:00:16,,
cowidev.vax.batch.ireland,0.45,True,2022-07-31T07:00:16,,
cowidev.vax.batch.israel,8.88,True,2022-07-31T07:00:25,,
cowidev.vax.batch.italy,11.1,True,2022-07-31T07:00:27,,
cowidev.vax.batch.japan,1.43,False,2022-07-31T07:03:21,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 241, in main
    Japan().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 225, in export
    df = self.read().pipe(self.pipeline_base)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 161, in read
    df_latest = self.read_latest().pipe(self.pipe_latest)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 91, in read_latest
    dfs.append(self._read_xlsx(self.source_url, self.sheets, self.metrics))
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 102, in _read_xlsx
    xlsx = pd.ExcelFile(tmp.name)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/excel/_base.py"", line 1195, in __init__
    raise ValueError(
ValueError: Excel file format cannot be determined, you must specify an engine manually.
","Excel file format cannot be determined, you must specify an engine manually."
cowidev.vax.batch.jersey,1.97,True,2022-07-31T07:00:27,,
cowidev.vax.batch.latvia,19.41,True,2022-07-31T07:00:47,,
cowidev.vax.batch.lithuania,1.29,True,2022-07-31T07:00:29,,
cowidev.vax.batch.luxembourg,1.52,True,2022-07-31T07:00:29,,
cowidev.vax.batch.malaysia,0.94,True,2022-07-31T07:00:29,,
cowidev.vax.batch.malta,0.66,True,2022-07-31T07:00:29,,
cowidev.vax.batch.netherlands,,,2022-07-31T07:00:29,,
cowidev.vax.batch.new_zealand,21.26,True,2022-07-31T07:00:50,,
cowidev.vax.batch.norway,0.41,True,2022-07-31T07:00:30,,
cowidev.vax.batch.peru,2.28,True,2022-07-31T07:00:32,,
cowidev.vax.batch.portugal,,,2022-07-31T07:00:30,,
cowidev.vax.batch.romania,8.01,True,2022-07-31T07:00:38,,
cowidev.vax.batch.saudi_arabia,8.14,True,2022-07-31T07:00:40,,
cowidev.vax.batch.singapore,2.34,True,2022-07-31T07:00:40,,
cowidev.vax.batch.slovakia,48.63,True,2022-07-31T07:01:28,,
cowidev.vax.batch.slovenia,1.98,True,2022-07-31T07:00:42,,
cowidev.vax.batch.south_korea,47.23,True,2022-07-31T07:01:29,,
cowidev.vax.batch.spc,19.57,True,2022-07-31T07:01:06,,
cowidev.vax.batch.sweden,13.65,True,2022-07-31T07:01:04,,
cowidev.vax.batch.switzerland,26.46,True,2022-07-31T07:01:30,,
cowidev.vax.batch.trinidad_and_tobago,1.56,True,2022-07-31T07:01:08,,
cowidev.vax.batch.ukraine,,,2022-07-31T07:01:08,,
cowidev.vax.batch.united_kingdom,8.02,True,2022-07-31T07:01:16,,
cowidev.vax.batch.united_states,25.55,True,2022-07-31T07:01:38,,
cowidev.vax.batch.uruguay,3.76,True,2022-07-31T07:01:20,,
cowidev.vax.batch.zimbabwe,1.64,True,2022-07-31T07:01:21,,
cowidev.vax.incremental.africacdc,,,2022-07-31T07:01:21,,
cowidev.vax.incremental.antigua_barbuda,6.54,True,2022-07-31T07:01:28,,
cowidev.vax.incremental.aruba,1.26,True,2022-07-31T07:01:29,,
cowidev.vax.incremental.azerbaijan,8.05,True,2022-07-31T07:01:37,,
cowidev.vax.incremental.bahrain,1.49,True,2022-07-31T07:01:30,,
cowidev.vax.incremental.bangladesh,15.23,True,2022-07-31T07:01:44,,
cowidev.vax.incremental.barbados,2.64,True,2022-07-31T07:01:33,,
cowidev.vax.incremental.brazil,0.07,True,2022-07-31T07:01:31,,
cowidev.vax.incremental.bulgaria,1.17,True,2022-07-31T07:01:32,,
cowidev.vax.incremental.china,48.09,True,2022-07-31T07:02:20,,
cowidev.vax.incremental.costa_rica,,,2022-07-31T07:01:33,,
cowidev.vax.incremental.croatia,0.14,True,2022-07-31T07:01:33,,
cowidev.vax.incremental.cuba,3.7,True,2022-07-31T07:01:37,,
cowidev.vax.incremental.curacao,0.39,True,2022-07-31T07:01:37,,
cowidev.vax.incremental.cyprus,0.86,True,2022-07-31T07:01:38,,
cowidev.vax.incremental.dominican_republic,2.36,False,2022-07-31T07:03:24,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 108, in main
    DominicanRepublic().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 64, in export
    data = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 23, in read
    with webdriver.Chrome(options=op) as driver:
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py"", line 76, in __init__
    RemoteWebDriver.__init__(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 321, in execute
    self.error_handler.check_response(response)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py"", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 101
Current browser version is 103.0.5060.134 with binary path /usr/bin/chromium-browser

","Message: session not created: This version of ChromeDriver only supports Chrome version 101
Current browser version is 103.0.5060.134 with binary path /usr/bin/chromium-browser
"
cowidev.vax.incremental.el_salvador,1.8,True,2022-07-31T07:01:39,,
cowidev.vax.incremental.faeroe_islands,0.35,True,2022-07-31T07:01:38,,
cowidev.vax.incremental.fiji,0.0,True,2022-07-31T07:01:38,,
cowidev.vax.incremental.finland,0.17,True,2022-07-31T07:01:38,,
cowidev.vax.incremental.gabon,,,2022-07-31T07:01:38,,
cowidev.vax.incremental.georgia,0.5,True,2022-07-31T07:01:39,,
cowidev.vax.incremental.greenland,0.47,True,2022-07-31T07:01:39,,
cowidev.vax.incremental.guatemala,,,2022-07-31T07:01:39,,
cowidev.vax.incremental.guernsey,0.14,True,2022-07-31T07:01:39,,
cowidev.vax.incremental.hungary,0.87,True,2022-07-31T07:01:40,,
cowidev.vax.incremental.iceland,0.51,True,2022-07-31T07:01:40,,
cowidev.vax.incremental.india,0.73,True,2022-07-31T07:01:40,,
cowidev.vax.incremental.iran,1.83,True,2022-07-31T07:01:42,,
cowidev.vax.incremental.isle_of_man,0.77,True,2022-07-31T07:01:41,,
cowidev.vax.incremental.jamaica,2.92,False,2022-07-31T07:03:27,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/jamaica.py"", line 57, in main
    Jamaica().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/jamaica.py"", line 52, in export
    data = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/jamaica.py"", line 17, in read
    return self._parse_data(soup)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/jamaica.py"", line 21, in _parse_data
    assert len(counters) == 6, ""New counter in dashboard?""
AssertionError: New counter in dashboard?
",New counter in dashboard?
cowidev.vax.incremental.kazakhstan,2.39,False,2022-07-31T07:03:29,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/kazakhstan.py"", line 78, in main
    Kazakhstan().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/kazakhstan.py"", line 73, in export
    df = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/kazakhstan.py"", line 17, in read
    with webdriver.Chrome(options=op) as driver:
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py"", line 76, in __init__
    RemoteWebDriver.__init__(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 321, in execute
    self.error_handler.check_response(response)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py"", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 101
Current browser version is 103.0.5060.134 with binary path /usr/bin/chromium-browser

","Message: session not created: This version of ChromeDriver only supports Chrome version 101
Current browser version is 103.0.5060.134 with binary path /usr/bin/chromium-browser
"
cowidev.vax.incremental.kosovo,1.62,True,2022-07-31T07:01:43,,
cowidev.vax.incremental.kyrgyzstan,0.85,True,2022-07-31T07:01:44,,
cowidev.vax.incremental.laos,2.14,True,2022-07-31T07:01:45,,
cowidev.vax.incremental.macao,2.37,False,2022-07-31T07:03:31,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 84, in main
    Macao().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 70, in export
    data = self.read()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 16, in read
    with get_driver() as driver:
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 161, in get_driver
    driver = webdriver.Chrome(options=options)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py"", line 76, in __init__
    RemoteWebDriver.__init__(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 321, in execute
    self.error_handler.check_response(response)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py"", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 101
Current browser version is 103.0.5060.134 with binary path /usr/bin/chromium-browser

","Message: session not created: This version of ChromeDriver only supports Chrome version 101
Current browser version is 103.0.5060.134 with binary path /usr/bin/chromium-browser
"
cowidev.vax.incremental.moldova,1.22,True,2022-07-31T07:01:46,,
cowidev.vax.incremental.monaco,30.22,True,2022-07-31T07:02:15,,
cowidev.vax.incremental.mongolia,0.79,True,2022-07-31T07:01:46,,
cowidev.vax.incremental.montenegro,10.24,True,2022-07-31T07:01:56,,
cowidev.vax.incremental.morocco,,,2022-07-31T07:01:46,,
cowidev.vax.incremental.myanmar,,,2022-07-31T07:01:46,,
cowidev.vax.incremental.nepal,,,2022-07-31T07:01:46,,
cowidev.vax.incremental.north_macedonia,,,2022-07-31T07:01:46,,
cowidev.vax.incremental.northern_cyprus,0.82,True,2022-07-31T07:01:47,,
cowidev.vax.incremental.paho,3.08,False,2022-07-31T07:03:34,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 191, in main
    PAHO().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 186, in export
    df = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 37, in read
    df = self._parse_data(url)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 46, in _parse_data
    with get_driver(download_folder=self._download_path) as driver:
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 161, in get_driver
    driver = webdriver.Chrome(options=options)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py"", line 76, in __init__
    RemoteWebDriver.__init__(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 321, in execute
    self.error_handler.check_response(response)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py"", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 101
Current browser version is 103.0.5060.134 with binary path /usr/bin/chromium-browser

","Message: session not created: This version of ChromeDriver only supports Chrome version 101
Current browser version is 103.0.5060.134 with binary path /usr/bin/chromium-browser
"
cowidev.vax.incremental.pakistan,1.66,True,2022-07-31T07:01:49,,
cowidev.vax.incremental.philippines,,,2022-07-31T07:01:49,,
cowidev.vax.incremental.poland,0.28,True,2022-07-31T07:01:49,,
cowidev.vax.incremental.qatar,,,2022-07-31T07:01:49,,
cowidev.vax.incremental.russia,0.5,False,2022-07-31T07:03:35,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 64, in main
    data = read(source).pipe(pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 11, in read
    soup = get_soup(source)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://gogov.ru/articles/covid-v-stats not reached! Error code 502 Bad Gateway
",Source https://gogov.ru/articles/covid-v-stats not reached! Error code 502 Bad Gateway
cowidev.vax.incremental.saint_lucia,,,2022-07-31T07:01:50,,
cowidev.vax.incremental.serbia,6.41,True,2022-07-31T07:01:56,,
cowidev.vax.incremental.south_africa,8.45,True,2022-07-31T07:01:58,,
cowidev.vax.incremental.spain,3.05,True,2022-07-31T07:01:59,,
cowidev.vax.incremental.sri_lanka,,,2022-07-31T07:01:56,,
cowidev.vax.incremental.suriname,2.39,False,2022-07-31T07:03:37,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/suriname.py"", line 57, in main
    data = read(source).pipe(pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/suriname.py"", line 13, in read
    with get_driver() as driver:
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 161, in get_driver
    driver = webdriver.Chrome(options=options)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py"", line 76, in __init__
    RemoteWebDriver.__init__(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 321, in execute
    self.error_handler.check_response(response)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py"", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 101
Current browser version is 103.0.5060.134 with binary path /usr/bin/chromium-browser

","Message: session not created: This version of ChromeDriver only supports Chrome version 101
Current browser version is 103.0.5060.134 with binary path /usr/bin/chromium-browser
"
cowidev.vax.incremental.taiwan,11.19,True,2022-07-31T07:02:09,,
cowidev.vax.incremental.thailand,2.8,True,2022-07-31T07:02:01,,
cowidev.vax.incremental.turkey,0.8,True,2022-07-31T07:02:00,,
cowidev.vax.incremental.united_arab_emirates,,,2022-07-31T07:02:00,,
cowidev.vax.incremental.vietnam,,,2022-07-31T07:02:00,,
cowidev.vax.incremental.who,5.85,True,2022-07-31T07:02:05,,
cowidev.vax.incremental.zambia,0.81,True,2022-07-31T07:02:02,,
