module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,1.58,False,2022-08-04T07:02:53,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/argentina.py"", line 227, in main
    Argentina().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/argentina.py"", line 203, in export
    df_base = self.read().pipe(self.pipeline_base)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/argentina.py"", line 189, in pipeline_base
    return df.pipe(self.pipe_base_vaccines).pipe(self.pipe_base_cumsum).pipe(self.pipe_base_metrics)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/argentina.py"", line 87, in pipe_base_vaccines
    raise ValueError(f""Unknown vaccines detected! {vaccines_wrong}"")
ValueError: Unknown vaccines detected! {'Moderna Pediátrica'}
",Unknown vaccines detected! {'Moderna Pediátrica'}
cowidev.vax.batch.australia,2.3,True,2022-08-04T07:00:14,,
cowidev.vax.batch.austria,,,2022-08-04T07:00:11,,
cowidev.vax.batch.belgium,3.02,True,2022-08-04T07:00:14,,
cowidev.vax.batch.bolivia,2.22,True,2022-08-04T07:00:14,,
cowidev.vax.batch.canada,6.27,True,2022-08-04T07:00:18,,
cowidev.vax.batch.chile,1.15,True,2022-08-04T07:00:15,,
cowidev.vax.batch.czechia,4.14,True,2022-08-04T07:00:18,,
cowidev.vax.batch.denmark,4.25,True,2022-08-04T07:00:18,,
cowidev.vax.batch.ecdc,60.1,False,2022-08-04T07:03:53,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 96, in create_connection
    raise err
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 699, in urlopen
    httplib_response = self._make_request(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 382, in _make_request
    self._validate_conn(conn)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 1010, in _validate_conn
    conn.connect()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 358, in connect
    conn = self._new_conn()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f989d372e80>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 755, in urlopen
    retries = retries.increment(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/retry.py"", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f989d372e80>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 506, in main
    ECDC().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 496, in export
    df = self.read().pipe(self.pipe_base)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 111, in read
    df = read_csv_from_url(self.source_url, timeout=30)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/download.py"", line 39, in read_csv_from_url
    download_file_from_url(url, tmp.name, timeout=timeout, verify=verify, ciphers_low=ciphers_low)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/download.py"", line 52, in download_file_from_url
    r = requests.get(url, stream=True, timeout=timeout, verify=verify)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f989d372e80>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)'))
","HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f989d372e80>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)'))"
cowidev.vax.batch.ecuador,1.46,True,2022-08-04T07:00:16,,
cowidev.vax.batch.estonia,1.3,True,2022-08-04T07:00:18,,
cowidev.vax.batch.france,0.59,True,2022-08-04T07:00:18,,
cowidev.vax.batch.germany,2.13,True,2022-08-04T07:00:20,,
cowidev.vax.batch.greece,2.85,True,2022-08-04T07:00:21,,
cowidev.vax.batch.hong_kong,14.22,True,2022-08-04T07:00:32,,
cowidev.vax.batch.indonesia,,,2022-08-04T07:00:18,,
cowidev.vax.batch.ireland,0.35,True,2022-08-04T07:00:19,,
cowidev.vax.batch.israel,8.76,True,2022-08-04T07:00:28,,
cowidev.vax.batch.italy,12.62,True,2022-08-04T07:00:32,,
cowidev.vax.batch.japan,0.52,False,2022-08-04T07:03:53,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 237, in main
    Japan().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 221, in export
    df = self.read().pipe(self.pipeline_base)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 157, in read
    df_latest = self.read_latest().pipe(self.pipe_latest)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 89, in read_latest
    dfs.append(self._read_xlsx(self.source_url, self.sheets, self.metrics))
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 98, in _read_xlsx
    xlsx = pd.ExcelFile(tmp.name)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/excel/_base.py"", line 1195, in __init__
    raise ValueError(
ValueError: Excel file format cannot be determined, you must specify an engine manually.
","Excel file format cannot be determined, you must specify an engine manually."
cowidev.vax.batch.jersey,2.41,True,2022-08-04T07:00:30,,
cowidev.vax.batch.latvia,23.26,True,2022-08-04T07:00:53,,
cowidev.vax.batch.lithuania,1.41,True,2022-08-04T07:00:34,,
cowidev.vax.batch.luxembourg,2.25,True,2022-08-04T07:00:35,,
cowidev.vax.batch.malaysia,0.77,True,2022-08-04T07:00:33,,
cowidev.vax.batch.malta,0.89,True,2022-08-04T07:00:34,,
cowidev.vax.batch.netherlands,,,2022-08-04T07:00:34,,
cowidev.vax.batch.new_zealand,8.1,True,2022-08-04T07:00:42,,
cowidev.vax.batch.norway,0.24,True,2022-08-04T07:00:34,,
cowidev.vax.batch.peru,2.14,True,2022-08-04T07:00:37,,
cowidev.vax.batch.portugal,,,2022-08-04T07:00:35,,
cowidev.vax.batch.romania,6.83,True,2022-08-04T07:00:41,,
cowidev.vax.batch.saudi_arabia,8.1,True,2022-08-04T07:00:45,,
cowidev.vax.batch.singapore,2.7,True,2022-08-04T07:00:44,,
cowidev.vax.batch.slovakia,60.8,True,2022-08-04T07:01:43,,
cowidev.vax.batch.slovenia,1.46,True,2022-08-04T07:00:46,,
cowidev.vax.batch.south_korea,39.81,True,2022-08-04T07:01:24,,
cowidev.vax.batch.spc,10.18,True,2022-08-04T07:00:56,,
cowidev.vax.batch.sweden,15.18,True,2022-08-04T07:01:08,,
cowidev.vax.batch.switzerland,34.28,True,2022-08-04T07:01:30,,
cowidev.vax.batch.trinidad_and_tobago,1.49,True,2022-08-04T07:01:10,,
cowidev.vax.batch.ukraine,,,2022-08-04T07:01:10,,
cowidev.vax.batch.united_kingdom,8.5,True,2022-08-04T07:01:18,,
cowidev.vax.batch.united_states,35.55,True,2022-08-04T07:01:50,,
cowidev.vax.batch.uruguay,2.79,True,2022-08-04T07:01:21,,
cowidev.vax.batch.zimbabwe,1.02,True,2022-08-04T07:01:22,,
cowidev.vax.incremental.africacdc,,,2022-08-04T07:01:22,,
cowidev.vax.incremental.antigua_barbuda,4.01,True,2022-08-04T07:01:26,,
cowidev.vax.incremental.aruba,1.32,True,2022-08-04T07:01:26,,
cowidev.vax.incremental.azerbaijan,13.48,True,2022-08-04T07:01:39,,
cowidev.vax.incremental.bahrain,4.57,True,2022-08-04T07:01:31,,
cowidev.vax.incremental.bangladesh,20.16,True,2022-08-04T07:01:50,,
cowidev.vax.incremental.barbados,11.94,True,2022-08-04T07:01:43,,
cowidev.vax.incremental.brazil,2.25,True,2022-08-04T07:01:41,,
cowidev.vax.incremental.bulgaria,2.03,True,2022-08-04T07:01:44,,
cowidev.vax.incremental.china,44.96,True,2022-08-04T07:02:28,,
cowidev.vax.incremental.costa_rica,,,2022-08-04T07:01:43,,
cowidev.vax.incremental.croatia,0.16,True,2022-08-04T07:01:43,,
cowidev.vax.incremental.cuba,2.29,True,2022-08-04T07:01:45,,
cowidev.vax.incremental.curacao,0.37,True,2022-08-04T07:01:44,,
cowidev.vax.incremental.cyprus,1.06,True,2022-08-04T07:01:45,,
cowidev.vax.incremental.dominican_republic,6.49,True,2022-08-04T07:01:51,,
cowidev.vax.incremental.el_salvador,0.92,True,2022-08-04T07:01:46,,
cowidev.vax.incremental.faeroe_islands,0.38,True,2022-08-04T07:01:46,,
cowidev.vax.incremental.fiji,0.0,True,2022-08-04T07:01:46,,
cowidev.vax.incremental.finland,0.25,True,2022-08-04T07:01:47,,
cowidev.vax.incremental.gabon,,,2022-08-04T07:01:47,,
cowidev.vax.incremental.georgia,0.79,True,2022-08-04T07:01:48,,
cowidev.vax.incremental.greenland,0.53,True,2022-08-04T07:01:48,,
cowidev.vax.incremental.guatemala,,,2022-08-04T07:01:48,,
cowidev.vax.incremental.guernsey,0.23,True,2022-08-04T07:01:48,,
cowidev.vax.incremental.hungary,0.91,True,2022-08-04T07:01:49,,
cowidev.vax.incremental.iceland,0.3,True,2022-08-04T07:01:50,,
cowidev.vax.incremental.india,0.93,True,2022-08-04T07:01:50,,
cowidev.vax.incremental.iran,2.04,True,2022-08-04T07:01:52,,
cowidev.vax.incremental.isle_of_man,0.85,True,2022-08-04T07:01:51,,
cowidev.vax.incremental.jamaica,2.4,True,2022-08-04T07:01:53,,
cowidev.vax.incremental.kazakhstan,9.84,True,2022-08-04T07:02:01,,
cowidev.vax.incremental.kosovo,1.13,True,2022-08-04T07:01:53,,
cowidev.vax.incremental.kyrgyzstan,2.19,True,2022-08-04T07:01:54,,
cowidev.vax.incremental.laos,2.13,True,2022-08-04T07:01:55,,
cowidev.vax.incremental.macao,16.89,True,2022-08-04T07:02:10,,
cowidev.vax.incremental.moldova,0.9,True,2022-08-04T07:01:55,,
cowidev.vax.incremental.monaco,27.3,True,2022-08-04T07:02:22,,
cowidev.vax.incremental.mongolia,0.88,True,2022-08-04T07:01:56,,
cowidev.vax.incremental.montenegro,0.1,True,2022-08-04T07:01:56,,
cowidev.vax.incremental.morocco,,,2022-08-04T07:01:56,,
cowidev.vax.incremental.myanmar,,,2022-08-04T07:01:56,,
cowidev.vax.incremental.nepal,,,2022-08-04T07:01:56,,
cowidev.vax.incremental.north_macedonia,,,2022-08-04T07:01:56,,
cowidev.vax.incremental.northern_cyprus,0.87,True,2022-08-04T07:01:57,,
cowidev.vax.incremental.paho,53.92,True,2022-08-04T07:02:51,,
cowidev.vax.incremental.pakistan,1.36,True,2022-08-04T07:02:02,,
cowidev.vax.incremental.philippines,,,2022-08-04T07:02:02,,
cowidev.vax.incremental.poland,0.14,True,2022-08-04T07:02:02,,
cowidev.vax.incremental.qatar,,,2022-08-04T07:02:02,,
cowidev.vax.incremental.russia,0.43,False,2022-08-04T07:03:54,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 64, in main
    data = read(source).pipe(pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 11, in read
    soup = get_soup(source)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://gogov.ru/articles/covid-v-stats not reached! Error code 502 Bad Gateway
",Source https://gogov.ru/articles/covid-v-stats not reached! Error code 502 Bad Gateway
cowidev.vax.incremental.saint_lucia,,,2022-08-04T07:02:03,,
cowidev.vax.incremental.serbia,6.6,True,2022-08-04T07:02:10,,
cowidev.vax.incremental.south_africa,8.25,True,2022-08-04T07:02:18,,
cowidev.vax.incremental.spain,4.54,True,2022-08-04T07:02:14,,
cowidev.vax.incremental.sri_lanka,,,2022-08-04T07:02:14,,
cowidev.vax.incremental.suriname,15.24,True,2022-08-04T07:02:30,,
cowidev.vax.incremental.taiwan,9.06,True,2022-08-04T07:02:27,,
cowidev.vax.incremental.thailand,1.43,True,2022-08-04T07:02:23,,
cowidev.vax.incremental.turkey,0.52,True,2022-08-04T07:02:24,,
cowidev.vax.incremental.united_arab_emirates,,,2022-08-04T07:02:24,,
cowidev.vax.incremental.vietnam,,,2022-08-04T07:02:24,,
cowidev.vax.incremental.who,4.9,True,2022-08-04T07:02:29,,
cowidev.vax.incremental.zambia,0.88,True,2022-08-04T07:02:28,,
