module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,3.9,True,2022-09-17T07:00:14,,
cowidev.vax.batch.australia,2.15,True,2022-09-17T07:00:13,,
cowidev.vax.batch.austria,2.6,True,2022-09-17T07:00:13,,
cowidev.vax.batch.belgium,2.55,True,2022-09-17T07:00:13,,
cowidev.vax.batch.bolivia,2.64,True,2022-09-17T07:00:13,,
cowidev.vax.batch.canada,7.3,False,2022-09-17T07:03:50,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 260, in main
    Canada().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 247, in export
    df_man = df_man.pipe(self.pipeline_manufacturer)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 179, in pipeline_manufacturer
    df = df[df.total_vaccinations > 0].replace(self.vaccine_mapping).dropna()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/ops/common.py"", line 69, in new_method
    return method(self, other)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/arraylike.py"", line 48, in __gt__
    return self._cmp_method(other, operator.gt)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/series.py"", line 5502, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/ops/array_ops.py"", line 284, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/ops/array_ops.py"", line 73, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
  File ""pandas/_libs/ops.pyx"", line 107, in pandas._libs.ops.scalar_compare
TypeError: '>' not supported between instances of 'str' and 'int'
",'>' not supported between instances of 'str' and 'int'
cowidev.vax.batch.chile,1.15,True,2022-09-17T07:00:14,,
cowidev.vax.batch.czechia,4.27,True,2022-09-17T07:00:17,,
cowidev.vax.batch.denmark,2.14,True,2022-09-17T07:00:15,,
cowidev.vax.batch.ecdc,116.44,True,2022-09-17T07:02:11,,
cowidev.vax.batch.ecuador,1.7,True,2022-09-17T07:00:16,,
cowidev.vax.batch.estonia,1.2,True,2022-09-17T07:00:16,,
cowidev.vax.batch.france,0.86,True,2022-09-17T07:00:17,,
cowidev.vax.batch.germany,2.06,True,2022-09-17T07:00:19,,
cowidev.vax.batch.greece,2.68,True,2022-09-17T07:00:20,,
cowidev.vax.batch.hong_kong,11.62,True,2022-09-17T07:00:29,,
cowidev.vax.batch.indonesia,,,2022-09-17T07:00:19,,
cowidev.vax.batch.ireland,0.18,True,2022-09-17T07:00:19,,
cowidev.vax.batch.israel,6.27,True,2022-09-17T07:00:25,,
cowidev.vax.batch.italy,9.87,True,2022-09-17T07:00:29,,
cowidev.vax.batch.japan,1.21,False,2022-09-17T07:03:51,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 236, in main
    Japan().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 220, in export
    df = self.read().pipe(self.pipeline_base)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 156, in read
    df_latest = self.read_latest().pipe(self.pipe_latest)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 88, in read_latest
    dfs.append(self._read_xlsx(self.source_url, self.sheets, self.metrics))
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 97, in _read_xlsx
    xlsx = pd.ExcelFile(url)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/excel/_base.py"", line 1191, in __init__
    ext = inspect_excel_format(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/excel/_base.py"", line 1070, in inspect_excel_format
    with get_handle(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/common.py"", line 609, in get_handle
    ioargs = _get_filepath_or_buffer(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/common.py"", line 312, in _get_filepath_or_buffer
    with urlopen(req_info) as req:
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/common.py"", line 212, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 214, in urlopen
    return opener.open(url, data, timeout)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 523, in open
    response = meth(req, response)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 632, in http_response
    response = self.parent.error(
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 561, in error
    return self._call_chain(*args)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 494, in _call_chain
    result = func(*args)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
",HTTP Error 404: Not Found
cowidev.vax.batch.jersey,1.13,True,2022-09-17T07:00:29,,
cowidev.vax.batch.latvia,26.21,True,2022-09-17T07:00:55,,
cowidev.vax.batch.lithuania,2.31,True,2022-09-17T07:00:32,,
cowidev.vax.batch.luxembourg,1.59,True,2022-09-17T07:00:31,,
cowidev.vax.batch.malaysia,1.25,True,2022-09-17T07:00:31,,
cowidev.vax.batch.malta,1.35,True,2022-09-17T07:00:32,,
cowidev.vax.batch.netherlands,,,2022-09-17T07:00:31,,
cowidev.vax.batch.new_zealand,27.61,True,2022-09-17T07:00:59,,
cowidev.vax.batch.norway,1.23,True,2022-09-17T07:00:33,,
cowidev.vax.batch.peru,3.87,True,2022-09-17T07:00:36,,
cowidev.vax.batch.portugal,,,2022-09-17T07:00:33,,
cowidev.vax.batch.romania,27.15,True,2022-09-17T07:01:00,,
cowidev.vax.batch.saudi_arabia,5.87,True,2022-09-17T07:00:42,,
cowidev.vax.batch.singapore,5.01,True,2022-09-17T07:00:47,,
cowidev.vax.batch.slovakia,79.52,True,2022-09-17T07:02:07,,
cowidev.vax.batch.slovenia,4.6,True,2022-09-17T07:01:00,,
cowidev.vax.batch.south_korea,68.82,True,2022-09-17T07:02:08,,
cowidev.vax.batch.spc,23.18,True,2022-09-17T07:01:23,,
cowidev.vax.batch.sweden,14.96,True,2022-09-17T07:01:15,,
cowidev.vax.batch.switzerland,51.72,True,2022-09-17T07:02:07,,
cowidev.vax.batch.trinidad_and_tobago,2.1,True,2022-09-17T07:01:25,,
cowidev.vax.batch.ukraine,,,2022-09-17T07:01:25,,
cowidev.vax.batch.united_kingdom,12.42,True,2022-09-17T07:01:37,,
cowidev.vax.batch.united_states,38.83,True,2022-09-17T07:02:16,,
cowidev.vax.batch.uruguay,2.74,True,2022-09-17T07:02:09,,
cowidev.vax.batch.zimbabwe,0.36,True,2022-09-17T07:02:07,,
cowidev.vax.incremental.africacdc,,,2022-09-17T07:02:07,,
cowidev.vax.incremental.antigua_barbuda,3.62,True,2022-09-17T07:02:11,,
cowidev.vax.incremental.aruba,0.96,True,2022-09-17T07:02:09,,
cowidev.vax.incremental.azerbaijan,,,2022-09-17T07:02:09,,
cowidev.vax.incremental.bahrain,2.15,True,2022-09-17T07:02:11,,
cowidev.vax.incremental.bangladesh,92.9,True,2022-09-17T07:03:42,,
cowidev.vax.incremental.barbados,4.16,True,2022-09-17T07:02:15,,
cowidev.vax.incremental.brazil,0.21,True,2022-09-17T07:02:11,,
cowidev.vax.incremental.bulgaria,0.98,True,2022-09-17T07:02:12,,
cowidev.vax.incremental.china,44.05,True,2022-09-17T07:02:55,,
cowidev.vax.incremental.costa_rica,,,2022-09-17T07:02:12,,
cowidev.vax.incremental.croatia,0.22,True,2022-09-17T07:02:12,,
cowidev.vax.incremental.cuba,2.39,True,2022-09-17T07:02:14,,
cowidev.vax.incremental.curacao,0.39,True,2022-09-17T07:02:15,,
cowidev.vax.incremental.cyprus,0.67,True,2022-09-17T07:02:15,,
cowidev.vax.incremental.dominican_republic,2.34,False,2022-09-17T07:03:53,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 108, in main
    DominicanRepublic().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 64, in export
    data = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 23, in read
    with webdriver.Chrome(options=op) as driver:
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py"", line 76, in __init__
    RemoteWebDriver.__init__(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 321, in execute
    self.error_handler.check_response(response)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py"", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 103
Current browser version is 105.0.5195.102 with binary path /usr/bin/chromium-browser

","Message: session not created: This version of ChromeDriver only supports Chrome version 103
Current browser version is 105.0.5195.102 with binary path /usr/bin/chromium-browser
"
cowidev.vax.incremental.el_salvador,1.03,True,2022-09-17T07:02:16,,
cowidev.vax.incremental.faeroe_islands,0.39,True,2022-09-17T07:02:17,,
cowidev.vax.incremental.fiji,0.0,True,2022-09-17T07:02:16,,
cowidev.vax.incremental.finland,0.24,True,2022-09-17T07:02:17,,
cowidev.vax.incremental.gabon,,,2022-09-17T07:02:16,,
cowidev.vax.incremental.georgia,0.47,True,2022-09-17T07:02:17,,
cowidev.vax.incremental.greenland,0.47,True,2022-09-17T07:02:17,,
cowidev.vax.incremental.guatemala,,,2022-09-17T07:02:17,,
cowidev.vax.incremental.guernsey,0.85,True,2022-09-17T07:02:18,,
cowidev.vax.incremental.hungary,3.56,True,2022-09-17T07:02:21,,
cowidev.vax.incremental.iceland,0.26,True,2022-09-17T07:02:17,,
cowidev.vax.incremental.india,0.89,True,2022-09-17T07:02:18,,
cowidev.vax.incremental.iran,,,2022-09-17T07:02:18,,
cowidev.vax.incremental.isle_of_man,1.53,True,2022-09-17T07:02:19,,
cowidev.vax.incremental.jamaica,2.13,True,2022-09-17T07:02:20,,
cowidev.vax.incremental.kazakhstan,2.34,False,2022-09-17T07:03:56,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/kazakhstan.py"", line 78, in main
    Kazakhstan().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/kazakhstan.py"", line 73, in export
    df = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/kazakhstan.py"", line 17, in read
    with webdriver.Chrome(options=op) as driver:
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py"", line 76, in __init__
    RemoteWebDriver.__init__(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 321, in execute
    self.error_handler.check_response(response)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py"", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 103
Current browser version is 105.0.5195.102 with binary path /usr/bin/chromium-browser

","Message: session not created: This version of ChromeDriver only supports Chrome version 103
Current browser version is 105.0.5195.102 with binary path /usr/bin/chromium-browser
"
cowidev.vax.incremental.kosovo,2.02,True,2022-09-17T07:02:22,,
cowidev.vax.incremental.kyrgyzstan,0.86,True,2022-09-17T07:02:21,,
cowidev.vax.incremental.laos,2.26,True,2022-09-17T07:02:24,,
cowidev.vax.incremental.macao,2.36,False,2022-09-17T07:03:58,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 86, in main
    Macao().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 72, in export
    data = self.read()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 16, in read
    with get_driver() as driver:
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 161, in get_driver
    driver = webdriver.Chrome(options=options)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py"", line 76, in __init__
    RemoteWebDriver.__init__(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 321, in execute
    self.error_handler.check_response(response)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py"", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 103
Current browser version is 105.0.5195.102 with binary path /usr/bin/chromium-browser

","Message: session not created: This version of ChromeDriver only supports Chrome version 103
Current browser version is 105.0.5195.102 with binary path /usr/bin/chromium-browser
"
cowidev.vax.incremental.moldova,40.09,False,2022-09-17T07:04:38,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 96, in create_connection
    raise err
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 699, in urlopen
    httplib_response = self._make_request(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 382, in _make_request
    self._validate_conn(conn)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 1010, in _validate_conn
    conn.connect()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 358, in connect
    conn = self._new_conn()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fa2f1fb12b0>, 'Connection to vaccinare.gov.md timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 755, in urlopen
    retries = retries.increment(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/retry.py"", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='vaccinare.gov.md', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa2f1fb12b0>, 'Connection to vaccinare.gov.md timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/moldova.py"", line 59, in main
    Moldova().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/moldova.py"", line 54, in export
    df = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/moldova.py"", line 17, in read
    soup = get_soup(self.source_url)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='vaccinare.gov.md', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa2f1fb12b0>, 'Connection to vaccinare.gov.md timed out. (connect timeout=20)'))
","HTTPSConnectionPool(host='vaccinare.gov.md', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa2f1fb12b0>, 'Connection to vaccinare.gov.md timed out. (connect timeout=20)'))"
cowidev.vax.incremental.monaco,35.84,True,2022-09-17T07:02:59,,
cowidev.vax.incremental.mongolia,0.79,True,2022-09-17T07:02:25,,
cowidev.vax.incremental.montenegro,0.09,True,2022-09-17T07:02:25,,
cowidev.vax.incremental.morocco,,,2022-09-17T07:02:25,,
cowidev.vax.incremental.myanmar,,,2022-09-17T07:02:25,,
cowidev.vax.incremental.nepal,,,2022-09-17T07:02:25,,
cowidev.vax.incremental.north_macedonia,,,2022-09-17T07:02:25,,
cowidev.vax.incremental.northern_cyprus,0.99,True,2022-09-17T07:02:26,,
cowidev.vax.incremental.paho,3.08,False,2022-09-17T07:04:41,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 191, in main
    PAHO().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 186, in export
    df = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 37, in read
    df = self._parse_data(url)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 46, in _parse_data
    with get_driver(download_folder=self._download_path) as driver:
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 161, in get_driver
    driver = webdriver.Chrome(options=options)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py"", line 76, in __init__
    RemoteWebDriver.__init__(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 321, in execute
    self.error_handler.check_response(response)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py"", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 103
Current browser version is 105.0.5195.102 with binary path /usr/bin/chromium-browser

","Message: session not created: This version of ChromeDriver only supports Chrome version 103
Current browser version is 105.0.5195.102 with binary path /usr/bin/chromium-browser
"
cowidev.vax.incremental.pakistan,1.32,True,2022-09-17T07:02:30,,
cowidev.vax.incremental.philippines,,,2022-09-17T07:02:30,,
cowidev.vax.incremental.poland,0.28,True,2022-09-17T07:02:31,,
cowidev.vax.incremental.qatar,,,2022-09-17T07:02:31,,
cowidev.vax.incremental.russia,0.92,False,2022-09-17T07:04:42,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 80, in main
    Russia().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 66, in export
    data = read(source).pipe(pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 11, in read
    soup = get_soup(source)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://gogov.ru/articles/covid-v-stats not reached! Error code 502 Bad Gateway
",Source https://gogov.ru/articles/covid-v-stats not reached! Error code 502 Bad Gateway
cowidev.vax.incremental.saint_lucia,,,2022-09-17T07:02:32,,
cowidev.vax.incremental.serbia,6.4,True,2022-09-17T07:02:38,,
cowidev.vax.incremental.south_africa,0.68,False,2022-09-17T07:04:43,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/south_africa.py"", line 274, in main
    SouthAfrica().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/south_africa.py"", line 256, in export
    df_main, df_manufacturer = self.read()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/south_africa.py"", line 150, in read
    df_main, df_manufacturer = self._parse_data()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/south_africa.py"", line 192, in _parse_data
    date = self._parse_date(date)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/south_africa.py"", line 207, in _parse_date
    return clean_date(date, ""%Y-%m-%dT%H:%M:%S.%fZ"")
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/clean/dates.py"", line 76, in clean_date
    dt = datetime.strptime(date_or_text, fmt) - timedelta(days=minus_days)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/_strptime.py"", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/_strptime.py"", line 349, in _strptime
    raise ValueError(""time data %r does not match format %r"" %
ValueError: time data '2022-09-17T07:02:40Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
",time data '2022-09-17T07:02:40Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
cowidev.vax.incremental.spain,6.92,True,2022-09-17T07:02:52,,
cowidev.vax.incremental.sri_lanka,,,2022-09-17T07:02:52,,
cowidev.vax.incremental.suriname,2.34,False,2022-09-17T07:04:45,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/suriname.py"", line 57, in main
    data = read(source).pipe(pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/suriname.py"", line 13, in read
    with get_driver() as driver:
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 161, in get_driver
    driver = webdriver.Chrome(options=options)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py"", line 76, in __init__
    RemoteWebDriver.__init__(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 321, in execute
    self.error_handler.check_response(response)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py"", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 103
Current browser version is 105.0.5195.102 with binary path /usr/bin/chromium-browser

","Message: session not created: This version of ChromeDriver only supports Chrome version 103
Current browser version is 105.0.5195.102 with binary path /usr/bin/chromium-browser
"
cowidev.vax.incremental.taiwan,8.1,False,2022-09-17T07:04:53,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 158, in main
    Taiwan().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 144, in export
    data = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 32, in read
    df = self._parse_table(url_pdf)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 69, in _parse_table
    raise ValueError(f""There are some unknown columns: {cols}"")
ValueError: There are some unknown columns: Index(['廠牌', '劑次', '9/16接種劑數', '累計至 9/16接種劑數'], dtype='object')
","There are some unknown columns: Index(['廠牌', '劑次', '9/16接種劑數', '累計至 9/16接種劑數'], dtype='object')"
cowidev.vax.incremental.thailand,3.87,True,2022-09-17T07:02:59,,
cowidev.vax.incremental.turkey,2.26,True,2022-09-17T07:03:02,,
cowidev.vax.incremental.united_arab_emirates,,,2022-09-17T07:02:59,,
cowidev.vax.incremental.vietnam,,,2022-09-17T07:02:59,,
cowidev.vax.incremental.who,5.01,True,2022-09-17T07:03:04,,
cowidev.vax.incremental.zambia,0.87,True,2022-09-17T07:03:03,,
